import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Leftbar from "@/components/Leftbar";
import Rightbar from "@/components/Rightbar";
import { Providers } from "../providers";
import { ViewTransitions } from "next-view-transitions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>

    <html lang="en">
      <body className={inter.className+"  "} >
      <Providers  >
        <main className=" flex">

        <Leftbar/>
        <main className="  flex-1 ">
        {children}  
        </main>
        <Rightbar />
        </main>

    </Providers>
      </body>
    </html>
    </ViewTransitions>
  );
}
